name: flutter_enterprise_template
description: A Flutter Enterprise Template 
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  
  # Network 
  dio: ^5.9.0  
  retrofit: ^4.9.2
  logger: ^2.6.2

  # Local Storage
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  firebase_remote_config: ^6.1.3  
  
  # Monitoring
  sentry_flutter: ^9.10.0
  
  # UI
  flutter_svg: ^2.2.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^17.0.1
  auto_route: ^11.1.0
  
  # Utils
  intl: ^0.20.2
  url_launcher: ^6.2.1
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  
  # Very Good Analysis (VGV's lint rules)
  very_good_analysis: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  injectable_generator: ^2.12.0
  retrofit_generator: ^10.2.1
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
          